# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: idormoy <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/23 09:36:18 by idormoy           #+#    #+#              #
#    Updated: 2018/07/23 09:43:52 by idormoy          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= ft_display_file

SRCS= main.c

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRCS)

clean:
	rm -f $(NAME)

fclean: clean

re: fclean $(NAME)
