# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: idormoy <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/17 19:53:46 by idormoy           #+#    #+#              #
#    Updated: 2018/07/19 22:42:02 by idormoy          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= do-op

SRC= calc_funs.c main.c print_fun.c str_fun.c

all: $(NAME)

$(NAME):
	@gcc -o $(NAME) $(SRC)

clean:
	@/bin/rm -f *.gch
	@/bin/rm -f $(NAME)
